flightnumber=input()
namerus=input()
nameeng=input()
townrus=input()
towneng=input()
print('Заканчивается посадка на рейс', flightnumber,'авиакомпании', namerus, 'до', townrus)
print('This is the final boading call for', flightnumber,'flight', nameeng, 'to', towneng)
