flightnumber=input()
namerus=input()
nameeng=input()
townrus=input()
towneng=input()
print('номер рейса:', flightnumber)
print('название авиакомпании (на русском языке):', namerus)
print('название авиакомпании (на английском языке):', nameeng)
print('город прилета (на русском языке):', townrus)
print('город прилета (на английском языке):', towneng)
print('Заканчивается посадка на рейс', flightnumber,'авиакомпании', namerus, 'до', townrus)
print('This is the final boading call for', flightnumber,'flight', nameeng, 'to', towneng)
